config/routes.rb
Rails.application.routes.draw do

  get    "signup" =>  'users#new'
  resources :users

  get "about" => 'static_pages#about'
 root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user=User.new
  end

  def create
  	@user=User.new(user_params)
  	if @user.save
  		flash[:success]="Welcome to The Website"
  		redirect_to @user
  	else
  		flash.now[:danger]="Please correct the errors below"
  		render :new
  	end
  end

  def edit
  	@user=User.find(params[:id])
  end

  def update
  	@user=User.find(params[:id])
  	if @user.update(user_params)
  		flash[:success]="Details updated"
  		redirect_to users_path
  	end
  end

  def index
  	@user=User.all
  end

  def show
  	@user=User.find(params[:id])
  end

  def destroy
  	@user=User.find(params[:id])
  	@user.delete
  	redirect_to users_path
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class= "container">
	<div class="center jumbotron">
	<%= render 'layouts/link'%>
	<h1 class= "h1">The Website</h1>

</div>
</div>

app/views/layouts/_link.html.erb
		
		<nav class="nav navbar-nav navbar-right">
			
			<%= link_to "Home", root_path, class: "btn btn-lg btn-primary" %>
		<%= link_to "New User", signup_path, class: "btn btn-lg btn-primary" %>
		<%= link_to "Profile",  "#", class: "btn btn-lg btn-primary" %>
		<%= link_to "About", about_path, class: "btn btn-lg btn-primary" %>
		<%= link_to "Users", users_path, class: "btn btn-lg btn-primary" %>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ACDRorProject1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	
	<%= render 'layouts/header'%>
	<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%flash.each do |msg_type, msg|%>
	<div class="alert alert-<%= msg_type %>"><%= msg %></div>
	<%end%>
</div>
</div>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<div class= "container">
	<p>The Website was created in 2016 to cater to the needs of people looking for The Website.</p>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec laoreet interdum semper. Proin ut neque volutpat, lacinia enim sit amet, luctus enim. Aenean sodales, est consequat sodales faucibus, tellus felis aliquet ipsum, vitae lobortis lorem magna ac neque. Fusce at ipsum lorem. Nunc gravida velit sit amet lorem viverra pulvinar. Curabitur nec quam sit amet velit sagittis efficitur. Proin pellentesque malesuada lorem, non dictum arcu fermentum non. Phasellus eu libero ut nunc rhoncus volutpat in vitae dui. Suspendisse potenti.</p>
</div>

app/views/static_pages/home.html.erb
<div class="container">
	
<p>This is the homepage of The Website. Here you will find basic information about this portal.</p>
<p>Vivamus lacinia accumsan tellus, eu luctus tellus facilisis sit amet. Integer libero risus, sollicitudin iaculis facilisis non, luctus nec leo. Suspendisse id laoreet arcu, ut pulvinar massa. Vestibulum id ultrices sapien. Pellentesque molestie tortor felis, tristique ultricies ante imperdiet ut. </p>
</div>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
  <div class="col-md-6 col-md-offset-3">

  	<%if @user.errors.any?%>
  	<% @user.errors.messages.each do |m|%>
  	<ul>
  	<li><%= m%></li>
  </ul>
  	<%end%>
  	<%end%>
  	<h1>Edit user details</h1>

<%= form_for @user do |user|%>
<%=user.label :name %>
<%=user.text_field :name, class: 'form-control' %>
<%=user.label :email %>
<%=user.email_field :email, class: 'form-control' %>


<%= user.submit "Save" , class: "btn btn-primary"%>
<%= %>
<%= %>
<%end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class = "row">
	<div class = "col col-md-8 col-md-offset-2"</div>
		<h1>All Users</h1>
			<table>
				<tr>
					<th class ="id">Id</th>
					<th>Name</th>
					<th>Email</th>
					<th>Edit</th>
					<th>Delete</th>
				</tr>
			<% @user.each do |u|%>
			<tr>
				<td><%=u.id%></td>
				<td><%=u.name%></td>
				<td><%=u.email%></td>
				<td><%=link_to "Edit", edit_user_path(u) %></td>
				<td><%=link_to "Delete", u, method: :delete, data: {confirm: "Are you sure?"}%></td>
			</tr>
			<%end%>
	</div>
</div>

app/views/users/new.html.erb
<div class="container">
<div class="row">
  <div class="col-md-6 col-md-offset-3">

  	<%if @user.errors.any?%>
  	<% @user.errors.messages.each do |m|%>
  	<ul>
  	<li><%= m%></li>
  </ul>
  	<%end%>
  	<%end%>
  	<h1>New User Registration</h1>

<%= form_for @user do |user|%>
<%=user.label :name %>
<%=user.text_field :name, class: 'form-control' %>
<%=user.label :email %>
<%=user.email_field :email, class: 'form-control' %>
<%= user.label :password%>
<%= user.text_field :password, class: 'form-control'%>
<%= user.label :password_confirmation%>
<%= user.text_field :password_confirmation, class: 'form-control' %>

<%= user.submit "Save" , class: "btn btn-primary"%>
<%= %>
<%= %>
<%end %>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container profile">
	<div class="">
			<h1 class = ""><%=@user.name.split[0]%>'s Profile</h1>
			</div>
	<div class = "row">

		<div class = "col col-md-4 col-md-offset-4">
			
			Name: 		<%= @user.name%><br>
			Email:  	<%= @user.email%>
		</div>
	</div>
</div>